### ISSUE TITLE
Doesn't work nicely with SwiftMailer

### ISSUE THREAD

**Issue by pryley** [Leeflets/leeflets#111]
Having problems integrating Swift Mailer with Leeflets because it conflicts with Swift Mailer's autoloader (spl_autoload_register).

**Comment by bradt** [comment]
What exactly is conflicting? Can you provide an error message?

**Comment by pryley** [comment]
Sure, here are the errors from the log.

```
PHP Warning:  require(/Users/Shared/Dropbox/Sites/greenzones.org/leeflets/core/controller/swift-mailTransport.php): failed to open stream: No such file or directory in /Users/Shared/Dropbox/Sites/greenzones.org/leeflets/core/library/leeflets.php on line 93, referer: http://greenzones.org/
PHP Fatal error:  require(): Failed opening required '/Users/Shared/Dropbox/Sites/greenzones.org/leeflets/core/controller/swift-mailTransport.php' (include_path='.:') in /Users/Shared/Dropbox/Sites/greenzones.org/leeflets/core/library/leeflets.php on line 93, referer: http://greenzones.org/
```

The only thing I can think of is a conflict with the Leeflets class autoloader.

I also tried using PHPMailer which gave the same errors.

I uploaded the addon for you to checkout (I also added cross-browser upload capability in the form using the [FileAPI](https://github.com/RubaXa/FileAPI) JS library):

https://github.com/pryley/Signup-Form/
