### ISSUE TITLE
Rework the panels to push the preview to the side instead of sliding over top

### ISSUE THREAD

**Issue by jmilone** [Leeflets/leeflets#13]

**Comment by lukemcdonald** [comment]
This is currently how the WP Customizer works and to be honest, it drives me a bit crazy. I work on a 13" Macbook air where screen real-estate is key. If a design has responsive styles set, the admin panel pushing the content to the side tends to initiate set the responsive styles into effect. Unless the content is updated in real-time (which would be a nice addition down the road), there really isn't a great need to see the full site and the panel covering the content shouldn't be too obstructive.

I noticed on WP.com, they have been working on a different style of theme customizer which is pretty nice. This customizer's panels slide over the top of the content much like Leeflets but on the right side. I would like to think the conscious decision behind that had something to do with the layout adjusting when responsive styles were present.

**Comment by bradt** [comment]
I was thinking that the preview could always be the same width as the browser window. When a panel slides open and pushes the preview to the right, it wouldn't resize it. It would just be clipped by the browser window. Better than the sliding overtop?

**Comment by lukemcdonald** [comment]
Yeah, that would be a cool effect. As far as better, that's debatable. Is there something about the slide over effect that is not liked?

**Comment by jptksc** [comment]
I personally have grown to like the slide-over effect. Would it be difficult to implement an option for this so that the user can choose their experience?

**Comment by lukemcdonald** [comment]
As food for thought, it might be good to keep a consistent user experience when interacting with Leeflets. An add-on might be a good route to implement different user experiences and options, possibly even admin "Skins".

**Comment by bradt** [comment]
Big change to the user experience here. What do you guys think?

**Comment by jptksc** [comment]
I have to say that I'm missing the slide-over effect. The push effect is driving me crazy (just my personal opinion). I would at least like the option to change this back to the slide-over if that's what I prefer as a user.

**Comment by bradt** [comment]
Hah, I guess it's a personal preference. I'm really liking the push effect over the slide over. Just seems so much neater to me. I find I can see the content change more easily as I save changes, rather than it mostly being hidden.

**Comment by jptksc** [comment]
I've been using it for a bit now and it's still driving me nuts. One of my biggest problems with it is that in preview/edit mode the template doesn't resize if I change my browser width (you need to refresh).

**Comment by bradt** [comment]
Ahhh...that can certainly be fixed. I'll add a task for it. Is there anything else that should be improved with it?

**Comment by bradt** [comment]
Ahhh...that can certainly be fixed. I'll add a task for it. Is there
anything else that should be improved with it?
