### ISSUE TITLE
Fly Out Menu Bug

### ISSUE THREAD

**Issue by jmilone** [Leeflets/leeflets#2]
On a fresh install of Leeflets when I click on an inline edit area (Samuel Jackson Beer, for example) the control panel appears on the left, but the edit pane does not fly out.

When I add the debug code...

$this->debug = true;
$this->debug_display = true;

...to the config file, the pane starts working. This is happening in Chrome on a fresh install of Leeflets with the default theme.

**Comment by itsdavidmorgan** [comment]
Also happening in FF
