### ISSUE TITLE
Missing Admin Bar Icons

### ISSUE THREAD

**Issue by jptksc** [Leeflets/leeflets#32]
Just noticed with the latest version of Leeflets that the admin bar icons are missing. Haven't tested in debug mode, but this is what I get on a fresh install.
![Screenshot 2013-02-24 at 18 06 33](https://f.cloud.github.com/assets/177514/190469/35f7c870-7ef0-11e2-85f9-7126a4961eb4.png)

**Comment by lukemcdonald** [comment]
I noticed the same when I updated last night.

**Comment by itsdavidmorgan** [comment]
Yup, noticed the same thing when I updated this morning.

**Comment by jptksc** [comment]
Nice... all is good now.
