### ISSUE TITLE
Save Changes Button Overlap

### ISSUE THREAD

**Issue by itsdavidmorgan** [Leeflets/leeflets#33]
I noticed there is an overlap of the new save changes button with the latest update.

![Screen Shot 2013-02-25 at 2 01 48 PM](https://f.cloud.github.com/assets/1852322/193946/1201ced2-7f97-11e2-9983-b66755f69808.png)

**Comment by bradt** [comment]
This was only occurring in Firefox. Apparently you need the -moz prefix for box-sizing to work.

**Comment by jptksc** [comment]
Firefox is the new IE for me.

**Comment by bradt** [comment]
I think Firefox's JS performance recently jumped ahead of Chrome. I'm thinking of making the switch back to FF.
