### ISSUE TITLE
Clicked "Install Leeflets"... 404

### ISSUE THREAD

**Issue by CasJam** [Leeflets/leeflets#38]
Tried installing for the first time.  Entered email and password twice.  Then it goes to this page, which is a 404:

http://casjam.com/demo/leeflets/user/login/

... CORRECTION:  Reloading that page now works.  But the first time it loaded, upon clicking "Install", it was a 404.

**Comment by bradt** [comment]
Hey Brian, I'm having trouble recreating this issue. Can you try doing another clean install of Leeflets to see if it happens again?

**Comment by rossdev** [comment]
I have the same issue but reloading the page did not work.

http://leeflets.rossdev.com/leeflets/user/login/

**Comment by bradt** [comment]
Looks like you haven't yet installed Leeflets: http://leeflets.rossdev.com/leeflets/

**Comment by rossdev** [comment]
Sorry.. It was installed but I was in the process of trouble shooting. I
don't have access to SSH right now so I'll have to wait till tonight to
finish checking my server config.

**Comment by bradt** [comment]
If you're getting a 404 at http://leeflets.rossdev.com/leeflets/user/login/ with Leeflets installed, it's most likely an issue with your .htaccess file.

**Comment by rossdev** [comment]
Tried again with a fresh vps and no luck. http://ats1.rossdev.com/leeflets/user/login/
Looks like .htaccess is not getting created.

**Comment by rossdev** [comment]
Figured it out... I needed to enable rewrite in apache2

**Comment by hawaiiwp** [comment]
I got this error immediately after install, but re logging in allowed me to get into the site.

**Comment by jptksc** [comment]
You didn't have to do anything other than re-login?

**Comment by hawaiiwp** [comment]
No. Just re login and it was fine. 
—

**Comment by bradt** [comment]
I could not recreate this. Closing for now, but if you can recreate it, please let me know and we can try debugging your environment.
