### ISSUE TITLE
Editing the headline requires me to edit the button too?

### ISSUE THREAD

**Issue by CasJam** [Leeflets/leeflets#39]
Making my very first content edit after installation...

Clicked the top area, and wanted to change the big headline "A Simple Website Solution" to something else.  So I replaced that text and clicked "Save".  

It says the button text and URL are required, even though I didn't intend to edit those.

http://cl.ly/image/2s1x1D040q3Y

**Comment by bradt** [comment]
Fixed in 2d9a9d1
