### ISSUE TITLE
Close button on initial welcome screen not working.

### ISSUE THREAD

**Issue by lukemcdonald** [Leeflets/leeflets#4]
When launching Leeflets for the first time, there is a close button (X) in the upper right hand corner of Welcome "Install Leeflets" modal window. The button currently does not do anything when clicked, however, my guess is the button should not show as there is no point in closing the modal box as it contains required fields in order to get Leeflets installed.

![install-leeflets-modal](https://f.cloud.github.com/assets/299173/174278/bf29738c-7b03-11e2-8e34-510707b062c5.png)

**Comment by lukemcdonald** [comment]
The same goes for the next screen after clicking "Install Leeflets". 

![welcome-back-leeflets-modal](https://f.cloud.github.com/assets/299173/174285/4c770ac4-7b04-11e2-85ca-fb1caa411be1.png)

**Comment by jptksc** [comment]
Yeah, I'm thinking that should probably be removed all together, or maybe go to your home page if clicked. Thoughts?

**Comment by jmilone** [comment]
I think so as well. Remove or add a "Back to Site" link (probably near the bottom).
