### ISSUE TITLE
Scaling browser after load issues

### ISSUE THREAD

**Issue by itsdavidmorgan** [Leeflets/leeflets#45]
Seems to be a new bug after updating today... scaling the browser doesn't result in the site scaling with it. The scroll bar sticks if the browser is scaled wider. A white padding appears on the left if browser is scaled smaller (to mobile size).

**Comment by jptksc** [comment]
I'm experiencing the same problem.

**Comment by bradt** [comment]
I think there's already an issue for this: #36 ?
