### ISSUE TITLE
.htaccess issues getting "internal server error"

### ISSUE THREAD

**Issue by adampickering** [Leeflets/leeflets#49]
Theres an internal server error when the following lines are added to the default .htaccess file

In case this is on in php.ini
php_flag magic_quotes_gpc Off

Try bumping up these values if you're getting errors uploading large files
php_value post_max_size 50M
php_value upload_max_filesize 20M

As soon as I remove them, the internal server goes and I can proceed with the installation.

**Comment by bradt** [comment]
Thanks for reporting this Adam!
