### ISSUE TITLE
Hook analytics code to footer by default

### ISSUE THREAD

**Issue by lukemcdonald** [Leeflets/leeflets#5]
In both default themes, it appears the analytics code is inserted into the index page template. 

```
<?php $this->setting( 'analytics', 'code' ); ?>
<?php $this->hook->apply( 'footer' ); ?>
```

Because the Analytics option is a Core setting, would it be beneficial to hook the analytics code into the footer by default? This would eliminate devs having to add this line of code to each Leeflet template. I don't know enough about Leeflets to provide a pull request yet, otherwise I'ld give it a shot :)

**Comment by jptksc** [comment]
Yeah... I think that makes total sense.

**Comment by bradt** [comment]
I thought about this a bit and I wonder if we need an additional setting that asks if the analytics code should be in the header or footer. I believe most codes are supposed to go in the header now, aren't they?

**Comment by jptksc** [comment]
I'm pretty sure most are either/or, but the recommendation is typically the header.

**Comment by jmilone** [comment]
Seems like most say to put the code in the header these days - especially Google.

**Comment by bradt** [comment]
Cool, I've added an option to the settings to choose whether the analytics is output with the 'head' or 'footer' hook.
