### ISSUE TITLE
Can't view site when logged out

### ISSUE THREAD

**Issue by ghost** [Leeflets/leeflets#52]
I can't seem to be able to view the site when I'm logged out; it keeps taking me back to the login screen if I just go to my root path, even when I'm in an incognito window in Google Chrome.

I've tried resetting my local server software (MAMP) and clearing my browser's cache, and neither helped. I feel this would be a problem for non-admin visitors.

**Comment by jptksc** [comment]
Have you "published" your site (the check icon in the bottom left of the admin)? If so, can you provide a little more info as to how your installation is set up? For instance, if you installed leeflets here:

```
"localhost/leeflets/leeflets/"
```

you should be able to access your site here:

```
"localhost/leeflets/"
```

**Comment by bradt** [comment]
Sounds like you have installed Leeflets in the root of your site. It needs to be installed in a subdirectory. So, all the Leeflets files should be located at example.com/leeflets or example.com/admin or whatever you want to name the directory. Then when you publish, it will create an index.html file at example.com/index.html. Does that help? :)﻿

**Comment by ghost** [comment]
Yes, I had it installed in the root directory. I reinstalled Leeflets in a subdirectory, published, and now it works properly. Thanks guys!
