### ISSUE TITLE
Can't get content showing in custom template

### ISSUE THREAD

**Issue by ghost** [Leeflets/leeflets#53]
I'm attempting to build a custom template. I have been able to get the template working in the CMS, I can get an edit screen with the required fields working, but I can't get the "editable" content to display, and the text I enter into the CMS when testing won't save.

Here are some screenshots I've taken of my theme's index.php, meta_content.php, and sample.json,php:

![Screen shot 2013-03-14 at 6 04 25 PM](https://f.cloud.github.com/assets/723559/261428/3f8cbdbc-8cf3-11e2-862c-aa915e695dc0.png)
![Screen shot 2013-03-14 at 6 04 46 PM](https://f.cloud.github.com/assets/723559/261429/3f8fda24-8cf3-11e2-9026-bd14645b22fe.png)
![Screen shot 2013-03-14 at 6 04 34 PM](https://f.cloud.github.com/assets/723559/261430/4038030c-8cf3-11e2-9f6e-36d9919fee8a.png)

**Comment by bradt** [comment]
Try adding the following lines to your config.php file:

```
$this->debug = true;
$this->debug_display = true;
```

Any errors showing up for you?

**Comment by ghost** [comment]
I added the code, tried adding content, and it showed me this error:

```
Warning: array_merge(): Argument #1 is not an array in /Users/nicholas/Sites/admin/core/controller/content.php on line 21
```

**Comment by bradt** [comment]
Looks like there's an issue with your sample.json.php file. You're missing a comma.

I don't recommend creating the sample.json.php file manually. Instead, enter your content via the forms and save. This will create a content-templatename.json.php file in your /data folder. Once your sample content is the way you want it, just copy that file to your template folder and rename it to sample.json.php.

**Comment by ghost** [comment]
It all works now. Thank you!
