### ISSUE TITLE
Site Icon Setting (favicon)

### ISSUE THREAD

**Issue by lukemcdonald** [Leeflets/leeflets#6]
One question I often get asked in WP theme development is how to change the favicon. There really isn't a good favicon plugin out there for WP (that I've found). WordPress.com has an option in _Settings > Reading_ for users to upload a **Blog Picture / Icon** (another point towards Jason's remarks about an "identity crisis").

I was thinking it might be beneficial to add an option to the Site settings to allow for a **Site Icon** (a.k.a. Favicon). It would be easiest to add this to the _Meta information_ section; though it's not technically Site Meta. 

I've added this functionality to my local install but didn't want to push any updates if it's not a good idea/direction. Thoughts?

**Comment by jptksc** [comment]
Hmmm... never thought of that (always added the option on a theme level), but now that you mention it, it really does seem to make sense to add it as a core option.

**Comment by bradt** [comment]
Great idea!

**Comment by itsdavidmorgan** [comment]
Yeah, I agree. Great idea!

**Comment by itsdavidmorgan** [comment]
Glad to see this issue is finally getting closed, lol ;)
