### ISSUE TITLE
Issues On Install

### ISSUE THREAD

**Issue by armandmorin** [Leeflets/leeflets#61]
I've tried two separate servers and both came back with same response...

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/amnet/public_html/leeflets-master/index.php on line 4

Parse error: syntax error, unexpected T_STRING in /home/amnet/public_html/leeflets-master/index.php on line 4

Also, on localhost,  I've received follow error... 
Fatal error: Class '\Leeflets\Controller\Error' not found in C:\Users\Armand\Documents\Websites\www.blank.dev\leef\core\library\leeflets.php on line 84

Ideas?

**Comment by bradt** [comment]
Leeflets requires PHP 5.3 and up. It sounds like you're using an older version of PHP.

There is code to detect what version of PHP you are running, but it looks like it's now executing too late. I've created a new task to fix that bug: #65
