### ISSUE TITLE
Local instalation asking for FTP

### ISSUE THREAD

**Issue by DavidVII** [Leeflets/leeflets#63]
I watched the installation video and it seems I'm getting a section not seen in the video.

I'm getting the following message:

> Leeflets has detected that it does not have access to save files to the server. Please enter your FTP details below to continue.

I'm using MAMP to and have set up a host called leeflets.dev that includes all leeflets files.

I looked through the documentation, but I didn't see anything pertaining to the message above. Did I miss it?

**Comment by DavidVII** [comment]
I should also mention that this is causing the installation to fail. I can not continue to install this locally.

**Comment by bradt** [comment]
Hi David, I just tested installing a fresh copy of Leeflets on my local machine with MAMP and didn't get that message. Can you check the permissions on the folder where you installed the Leeflets files? It's possible that it is not writeable.

**Comment by DavidVII** [comment]
Hi Brad,
Yep, permission are all set to read and write. I thought maybe that was the issue too. I tried installing it three different times, but still no goose. Not sure what else I can do here... Any other suggestions?

**Comment by bradt** [comment]
Actually, did you install leeflets in a subfolder or in the root of the site? Your URL to Leeflets should be http://leeflets.dev/leeflets/.

**Comment by DavidVII** [comment]
I was just about to post.

The issue turned out to be my permissions again. I'm not really sure what the problem was, but I figured out a solution. I had to set the Owner under MAMP to "www"

![permissions](https://f.cloud.github.com/assets/504075/304766/acc55c58-9645-11e2-8158-fdd0ec99c3f4.png)

After doing that the FTP warning message went away.

**Comment by DavidVII** [comment]
Thanks for your help, Brad!

**Comment by bradt** [comment]
Ahh, yep, that would do it! :)
