### ISSUE TITLE
PHP errors when logged in

### ISSUE THREAD

**Issue by DavidVII** [Leeflets/leeflets#67]
I've installed on a live server and have found these 3 errors when logged in:

> Warning: Invalid argument supplied for foreach() in /leeflets/core/library/template.php on line 105
> 
> Warning: array_merge() [function.array-merge]: Argument # 2 is not an array in /leeflets/core/library/template.php on line 106
> 
> Warning: Invalid argument supplied for foreach() in /leeflets/core/library/template.php on line 84

I suspect this is something that will need to change in the template.php file, right?

**Comment by bradt** [comment]
Hmm, interesting...I'll see if I can recreate those errors.

**Comment by tatygrassini** [comment]
This can be fixed changing your server PHP version. In my case, I had to add the following to my `.htaccess` file.

```
Action php /cgi-php55/php
AddHandler php55 .php
```
