### ISSUE TITLE
Display error when failing to publish site locally

### ISSUE THREAD

**Issue by calvinf** [Leeflets/leeflets#68]
Hi,

I attempted to publish the site locally, but it failed.  I believe this was due to permissions issues.

Two problems here:

1) Even though the local directory for leeflets may be writeable, that doesn't mean the published file will be writable.  Check for write permissions on the resultant file.

2) If the existing file is writeable, but wasn't created by leeflets, a warning message should be provided before attempting to write to it.  This could be tracked by including a meta generator element or some other markup in the resultant file.

Thanks.

**Comment by bradt** [comment]
This should be two separate issues. I've created #72 to take care of the 2nd part.
