### ISSUE TITLE
Issue with Installation (Using MAMP PRO)

### ISSUE THREAD

**Issue by realph** [Leeflets/leeflets#76]
When I visit my server (dev.leef.com/leeflets) during installation I'm hit in the face with this error:

> The requested URL /leeflets was not found on this server.

So, I dumped the Leeflets install in a subfolder called "demo" and tried to access the installation via /demo, which brought me to the installation screen. Only problem I now seem to be having is this:

> Leeflets has detected that it does not have access to save files to the server. Please enter your FTP details below to continue.

I have no FTP as I'm trying to do this locally. Any ideas?

**Comment by bradt** [comment]
For your first issue, yes, Leeflets required installation in a subfolder.

For your second issue, check the user setting that MAMP Pro is running as...

![Screen Shot 2013-04-13 at 10 22 29 AM](https://f.cloud.github.com/assets/190095/376528/391fcd28-a43d-11e2-8060-0ba64e6a461f.png)

If you need it configured to run as www/mysql, then you will need to adjust your file permissions accordingly.
