### ISSUE TITLE
Local Mamp Pro HTTP Error 500

### ISSUE THREAD

**Issue by iarico** [Leeflets/leeflets#77]
I'm having troubles viewing leeflets locally. 

I have it running via MAMP Pro, in a subfolder, and on the same MAMP server and folder setup as Dropplets, which I can view with no troubles. 

demo/dropplets resolves as expected.
demo/leeflets returns a HTTP Error 500 error?

I can view files from within the directory, such as demo/leeflets/templates/koala/style.css and demo/leeflets/favicon.ico.

The php_error.log in Console is spitting out this error message ....

PHP Fatal error:  Class '\Leeflets\Controller\Error' not found in /Users/[MyUserNameHere]/demo/leeflets/core/library/leeflets.php on line 82

**Comment by iarico** [comment]
Update: Leeflets is alive locally.

I upgraded MAMP Pro to Version 2. Although I was testing MAMP Pro Version 1 with PHP 5.3, and I wasn't getting PHP min version warning message either? So I don't know what the issue was.

**Comment by bradt** [comment]
Very strange. Sounds like it could have been something in your Apache or PHP config.
