### ISSUE TITLE
Image upload and resizing support

### ISSUE THREAD

**Issue by jmilone** [Leeflets/leeflets#8]

**Comment by bradt** [comment]
Dudes, I've completely reworked the upload UI. I think it's much more intuitive now for drag/drop and selecting files. Pull the latest and let me know what you think.

I've also completed the image resizing stuff. You can now define 'versions' of an image when defining your fields in `meta-content.php`. In the Koala template, you'll see the following:

```
'icon' => array(
    'type' => 'image',
    'label' => 'Icon',
    'versions' => array(
        'icon@2x' => array(
            'width' => 202,
            'height' => 220,
            'crop' => array( 'center', 'center' )
        )
    )
)
```

So, when an image is uploaded for the icon, it will create another size 202 x 220, cropped center center, and append 'icon@2x' to the end of the filename. Unlike WP, you can actually define where the image is cropped. For example, if it's a headshot, you probably want `array( 'center', 'top' )` instead. Another feature that WP doesn't currently do is reading the EXIF data and rotating the image if necessary.

Next up, multi-file upload support. Should go quicker as I did a lot of the legwork reworking this other stuff.

**Comment by jptksc** [comment]
Holy crap! This is awesome.

**Comment by bradt** [comment]
:) ... I forgot to mention, it also now stores the files uploaded for a template in its own subfolder (i.e. uploads/template-name/). So if you want to remove all the files for a template you can just delete the whole folder.

**Comment by jmilone** [comment]
That's pretty awesome. Image-heavy templates will be much improved by this.

**Comment by lukemcdonald** [comment]
In the future, it would be cool to have the user define image position. Theoretically, it should be up to the user how the image should be displayed, not the developer. This is not true in all cases, though the majority of the time I think it would be. Of course, the functionality currently provided is great, though there is room to take it a bit futher.

A possible solution to allowing the user to define image placement could be allowing the user to drag/postion the image into place within an allotted width and height size after they upload the image. I've been on some sites that allow this type of functionality though I can't think of any offhand. This type of functionality would come in handy for images that are used as small icons or thumbnails (e.g. Koala template). Imagine the four icons in the Koala template were used as profile images. If the dev sets them to be aligned `center, center`, the top of the heads may get cut off. If the user could drag the image into place, all is well.

Another solution would be to allow the user to crop an image with a designated width and height set by the template. I believe Google does this in some cases, for example, adding a new profile image to your G+ profile (if I remember correctly).

It could be that the developer can set if the uploaded image can be positioned/cropped by the user. I'm not even sure if what I'm suggesting makes sense, and if so, if it's even possible. In any case, it's food for thought.

**Comment by bradt** [comment]
Yep, great suggestion! Added a new task for it: https://github.com/Leeflets/leeflets/issues/46
